---
-   name: prepare a host to use as a gate for MinFin
    hosts: jitsi

    vars:
        pkg_add:
            - socat
            - tmux
            - bat
            - ncat
            - kitty-terminfo
            - perl
            - ddclient
            - htop
            - certbot
            - git

    tasks:
        - name: read the variables from vault
          include_vars: vault.yaml

        - name: include the open variables
          include_vars: global_vars.yaml

          # APT update moved to separate playbook

        - name: install packages
          apt:
              name: "{{pkg_add}}"
              state: present

        - name: create a group for 'dgolub' user
          group:
              name: "dgolub"
              state: present

        - name: create a group for 'dgolub' user
          group:
              name: "docker"
              state: present

        # create password with openssl passwd -5 -stdin <<< "your_password_here"
        - name: create an user for me
          user:
              name:        "dgolub"
              group:       "dgolub"
              groups:      "sudo,users,docker"
              shell:       "/bin/bash"
              home:        "/home/dgolub"
              create_home: yes
              password:    "{{dgolub_passwd}}"
              update_password: on_create
              state:       present

        - name: copy SSH key file to target machine
          authorized_key:
              user:       dgolub
              manage_dir: yes
              exclusive:  yes
              key:        "{{dgolub_key}}"

        - name: enable passwordless SUDO for dgolub
          lineinfile:
              path: /etc/sudoers.d/10_dgolub-user
              create: yes
              mode: 0600
              state: present
              line: 'dgolub ALL=(ALL) NOPASSWD: ALL'

        - name: put TMUX config file to my user
          template:
              src:    Templates/tmux.conf
              dest:   /home/dgolub/.tmux.conf
              owner:  dgolub
              group:  dgolub
              mode:   0644
              backup: no

        - name: create ddclient configuration
          template:
              src: Templates/ddclient.conf
              dest: /etc/ddclient.conf
              owner: root
              group: root
              mode: 640
              backup: yes
